spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aws-test-local
    username: postgres
    password: password

  jpa:
      hibernate:
          ddl-auto: none
      show-sql: true
      properties:
          hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect